name: cr_calendar_example
description: Demonstrates how to use the cr_calendar plugin.

version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cr_calendar:
    path: ../

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true



